import { Recipe } from "./types";

/**
 * 30 recettes healthy et protéinées. Tous les prix (`estimatedPrice`) sont des
 * estimations basées sur des prix moyens en supermarché français (Lidl,
 * Carrefour, Auchan...) début 2025 — pas des prix exacts. Modifiables par
 * l'utilisateur dans l'app.
 */
export const recipes: Recipe[] = [
  {
    id: "bowl-poulet-riz-avocat",
    name: "Bowl poulet riz avocat",
    categories: ["dejeuner", "post-training"],
    portions: 1,
    prepTimeMin: 25,
    difficulty: "facile",
    tags: ["proteine", "gourmand"],
    calories: 620,
    protein: 45,
    carbs: 60,
    fat: 22,
    ingredients: [
      { name: "Blanc de poulet", quantity: 150, unit: "g", rayon: "proteines", estimatedPrice: 1.8, store: "Lidl" },
      { name: "Riz basmati", quantity: 80, unit: "g", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Avocat", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 1.0 },
      { name: "Tomates cerises", quantity: 80, unit: "g", rayon: "legumes", estimatedPrice: 0.6 },
      { name: "Sauce soja", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.1 },
    ],
    cheaperOption: "Remplacer l'avocat par du maïs en boîte.",
    fancierOption: "Ajouter des graines de sésame torréfiées et de la coriandre fraîche.",
  },
  {
    id: "salade-thon-oeufs-pdt",
    name: "Salade thon œufs pommes de terre",
    categories: ["dejeuner", "rapide"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["proteine", "budget-bas", "rapide"],
    calories: 480,
    protein: 38,
    carbs: 35,
    fat: 18,
    ingredients: [
      { name: "Thon au naturel (boîte)", quantity: 1, unit: "piece", rayon: "proteines", estimatedPrice: 1.1, store: "Lidl" },
      { name: "Œufs", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 0.5 },
      { name: "Pommes de terre", quantity: 200, unit: "g", rayon: "feculents", estimatedPrice: 0.5 },
      { name: "Salade verte", quantity: 50, unit: "g", rayon: "legumes", estimatedPrice: 0.4 },
      { name: "Vinaigrette légère", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.1 },
    ],
  },
  {
    id: "wrap-poulet-crudites-yaourt",
    name: "Wrap poulet crudités sauce yaourt",
    categories: ["dejeuner", "rapide"],
    portions: 1,
    prepTimeMin: 12,
    difficulty: "facile",
    tags: ["proteine", "rapide"],
    calories: 450,
    protein: 35,
    carbs: 40,
    fat: 14,
    ingredients: [
      { name: "Galette wrap complète", quantity: 1, unit: "piece", rayon: "feculents", estimatedPrice: 0.5 },
      { name: "Blanc de poulet cuit", quantity: 100, unit: "g", rayon: "proteines", estimatedPrice: 1.3 },
      { name: "Crudités (carotte, concombre)", quantity: 80, unit: "g", rayon: "legumes", estimatedPrice: 0.5 },
      { name: "Yaourt nature + épices", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "omelette-legumes-fromage-allege",
    name: "Omelette légumes fromage allégé",
    categories: ["petit-dejeuner", "diner", "rapide"],
    portions: 1,
    prepTimeMin: 10,
    difficulty: "facile",
    tags: ["proteine", "rapide", "moins-500kcal", "sans-gluten"],
    calories: 320,
    protein: 28,
    carbs: 8,
    fat: 20,
    ingredients: [
      { name: "Œufs", quantity: 3, unit: "piece", rayon: "proteines", estimatedPrice: 0.75 },
      { name: "Poivrons + champignons", quantity: 100, unit: "g", rayon: "legumes", estimatedPrice: 0.6 },
      { name: "Fromage râpé allégé", quantity: 30, unit: "g", rayon: "laitiers", estimatedPrice: 0.4 },
    ],
  },
  {
    id: "skyr-fruits-rouges-granola",
    name: "Skyr fruits rouges granola",
    categories: ["petit-dejeuner", "collation"],
    portions: 1,
    prepTimeMin: 3,
    difficulty: "facile",
    tags: ["proteine", "sans-cuisson", "rapide"],
    calories: 350,
    protein: 30,
    carbs: 35,
    fat: 8,
    ingredients: [
      { name: "Skyr nature", quantity: 200, unit: "g", rayon: "laitiers", estimatedPrice: 1.1, store: "Lidl" },
      { name: "Fruits rouges surgelés", quantity: 80, unit: "g", rayon: "surgeles", estimatedPrice: 0.6, store: "Picard" },
      { name: "Granola", quantity: 30, unit: "g", rayon: "feculents", estimatedPrice: 0.4 },
    ],
  },
  {
    id: "pates-completes-thon-tomate",
    name: "Pâtes complètes thon tomate",
    categories: ["dejeuner", "diner", "rapide"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["budget-bas", "rapide", "lidl"],
    calories: 520,
    protein: 32,
    carbs: 70,
    fat: 10,
    ingredients: [
      { name: "Pâtes complètes", quantity: 90, unit: "g", rayon: "feculents", estimatedPrice: 0.35, store: "Lidl" },
      { name: "Thon au naturel (boîte)", quantity: 1, unit: "piece", rayon: "proteines", estimatedPrice: 1.1, store: "Lidl" },
      { name: "Sauce tomate", quantity: 150, unit: "g", rayon: "sauces", estimatedPrice: 0.5, store: "Lidl" },
      { name: "Origan, ail", quantity: 1, unit: "cc", rayon: "epices", estimatedPrice: 0.05 },
    ],
  },
  {
    id: "patate-douce-poulet-fromage-blanc",
    name: "Patate douce poulet fromage blanc",
    categories: ["dejeuner", "diner", "meal-prep"],
    portions: 1,
    prepTimeMin: 30,
    difficulty: "moyen",
    tags: ["proteine", "gourmand", "meal-prep"],
    calories: 560,
    protein: 42,
    carbs: 50,
    fat: 16,
    ingredients: [
      { name: "Patate douce", quantity: 200, unit: "g", rayon: "feculents", estimatedPrice: 0.7 },
      { name: "Blanc de poulet", quantity: 150, unit: "g", rayon: "proteines", estimatedPrice: 1.8, store: "Lidl" },
      { name: "Fromage blanc 0%", quantity: 50, unit: "g", rayon: "laitiers", estimatedPrice: 0.3 },
      { name: "Épices paprika/cumin", quantity: 1, unit: "cc", rayon: "epices", estimatedPrice: 0.05 },
    ],
  },
  {
    id: "bowl-saumon-riz-concombre",
    name: "Bowl saumon riz concombre",
    categories: ["dejeuner"],
    portions: 1,
    prepTimeMin: 25,
    difficulty: "moyen",
    tags: ["proteine", "gourmand", "picard"],
    calories: 600,
    protein: 38,
    carbs: 55,
    fat: 24,
    ingredients: [
      { name: "Pavé de saumon surgelé", quantity: 130, unit: "g", rayon: "surgeles", estimatedPrice: 2.5, store: "Picard" },
      { name: "Riz basmati", quantity: 80, unit: "g", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Concombre", quantity: 80, unit: "g", rayon: "legumes", estimatedPrice: 0.3 },
      { name: "Sauce soja + sésame", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "soupe-legumes-oeufs",
    name: "Soupe légumes + œufs",
    categories: ["diner"],
    portions: 1,
    prepTimeMin: 20,
    difficulty: "facile",
    tags: ["vegetarien", "moins-500kcal", "leger-soir", "budget-bas"],
    calories: 280,
    protein: 18,
    carbs: 20,
    fat: 12,
    ingredients: [
      { name: "Légumes pour soupe (surgelés)", quantity: 300, unit: "g", rayon: "surgeles", estimatedPrice: 1.0, store: "Picard" },
      { name: "Œufs", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 0.5 },
      { name: "Bouillon de légumes", quantity: 1, unit: "cc", rayon: "epices", estimatedPrice: 0.1 },
    ],
  },
  {
    id: "sandwich-complet-dinde-avocat",
    name: "Sandwich complet dinde avocat",
    categories: ["dejeuner", "rapide"],
    portions: 1,
    prepTimeMin: 8,
    difficulty: "facile",
    tags: ["rapide", "proteine"],
    calories: 430,
    protein: 30,
    carbs: 40,
    fat: 15,
    ingredients: [
      { name: "Pain complet", quantity: 2, unit: "piece", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Blanc de dinde tranché", quantity: 80, unit: "g", rayon: "proteines", estimatedPrice: 1.4 },
      { name: "Avocat", quantity: 0.5, unit: "piece", rayon: "fruits", estimatedPrice: 0.5 },
      { name: "Salade", quantity: 20, unit: "g", rayon: "legumes", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "salade-caesar-healthy",
    name: "Salade César healthy",
    categories: ["dejeuner"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["proteine", "gourmand"],
    calories: 470,
    protein: 38,
    carbs: 20,
    fat: 24,
    ingredients: [
      { name: "Blanc de poulet", quantity: 130, unit: "g", rayon: "proteines", estimatedPrice: 1.6, store: "Lidl" },
      { name: "Salade romaine", quantity: 80, unit: "g", rayon: "legumes", estimatedPrice: 0.6 },
      { name: "Parmesan", quantity: 15, unit: "g", rayon: "laitiers", estimatedPrice: 0.5 },
      { name: "Croûtons", quantity: 20, unit: "g", rayon: "feculents", estimatedPrice: 0.2 },
      { name: "Sauce César allégée", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.25 },
    ],
  },
  {
    id: "riz-saute-oeufs-legumes",
    name: "Riz sauté œufs légumes",
    categories: ["dejeuner", "diner", "rapide"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["budget-bas", "vegetarien", "rapide"],
    calories: 460,
    protein: 18,
    carbs: 70,
    fat: 12,
    ingredients: [
      { name: "Riz cuit (veille ou surgelé)", quantity: 200, unit: "g", rayon: "feculents", estimatedPrice: 0.4 },
      { name: "Œufs", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 0.5 },
      { name: "Légumes sautés surgelés", quantity: 150, unit: "g", rayon: "surgeles", estimatedPrice: 0.6, store: "Picard" },
      { name: "Sauce soja", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.1 },
    ],
  },
  {
    id: "curry-poulet-leger",
    name: "Curry poulet léger",
    categories: ["diner", "meal-prep"],
    portions: 2,
    prepTimeMin: 30,
    difficulty: "moyen",
    tags: ["proteine", "gourmand", "meal-prep"],
    calories: 540,
    protein: 40,
    carbs: 40,
    fat: 20,
    ingredients: [
      { name: "Blanc de poulet", quantity: 300, unit: "g", rayon: "proteines", estimatedPrice: 3.6, store: "Lidl" },
      { name: "Lait de coco light", quantity: 200, unit: "ml", rayon: "sauces", estimatedPrice: 1.0 },
      { name: "Riz basmati", quantity: 150, unit: "g", rayon: "feculents", estimatedPrice: 0.5 },
      { name: "Curry en poudre", quantity: 1, unit: "cs", rayon: "epices", estimatedPrice: 0.1 },
      { name: "Légumes (poivron, oignon)", quantity: 150, unit: "g", rayon: "legumes", estimatedPrice: 0.7 },
    ],
  },
  {
    id: "assiette-kebab-healthy-maison",
    name: "Assiette kebab healthy maison",
    categories: ["dejeuner", "diner"],
    portions: 1,
    prepTimeMin: 20,
    difficulty: "moyen",
    tags: ["proteine", "gourmand"],
    calories: 580,
    protein: 42,
    carbs: 45,
    fat: 22,
    ingredients: [
      { name: "Émincé de poulet mariné", quantity: 150, unit: "g", rayon: "proteines", estimatedPrice: 2.0, store: "Lidl" },
      { name: "Salade, tomates, oignons", quantity: 100, unit: "g", rayon: "legumes", estimatedPrice: 0.5 },
      { name: "Riz ou pain pita", quantity: 100, unit: "g", rayon: "feculents", estimatedPrice: 0.4 },
      { name: "Sauce blanche allégée", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "porridge-avoine-banane-proteine",
    name: "Porridge avoine banane protéiné",
    categories: ["petit-dejeuner"],
    portions: 1,
    prepTimeMin: 8,
    difficulty: "facile",
    tags: ["proteine", "rapide", "budget-bas", "vegetarien"],
    calories: 420,
    protein: 25,
    carbs: 60,
    fat: 8,
    ingredients: [
      { name: "Flocons d'avoine", quantity: 60, unit: "g", rayon: "feculents", estimatedPrice: 0.25 },
      { name: "Lait demi-écrémé", quantity: 200, unit: "ml", rayon: "laitiers", estimatedPrice: 0.25 },
      { name: "Banane", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 0.3 },
      { name: "Whey protéine", quantity: 1, unit: "cs", rayon: "snacks", estimatedPrice: 0.6 },
    ],
  },
  {
    id: "pancakes-proteines-banane-oeufs",
    name: "Pancakes protéinés banane œufs",
    categories: ["petit-dejeuner"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["proteine", "gourmand"],
    calories: 450,
    protein: 28,
    carbs: 50,
    fat: 12,
    ingredients: [
      { name: "Œufs", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 0.5 },
      { name: "Banane", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 0.3 },
      { name: "Flocons d'avoine", quantity: 50, unit: "g", rayon: "feculents", estimatedPrice: 0.2 },
      { name: "Miel", quantity: 1, unit: "cc", rayon: "epices", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "toast-avocat-oeuf-poche",
    name: "Toast avocat œuf poché",
    categories: ["petit-dejeuner", "rapide"],
    portions: 1,
    prepTimeMin: 10,
    difficulty: "facile",
    tags: ["vegetarien", "rapide"],
    calories: 380,
    protein: 18,
    carbs: 30,
    fat: 20,
    ingredients: [
      { name: "Pain complet", quantity: 2, unit: "piece", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Avocat", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 1.0 },
      { name: "Œuf", quantity: 1, unit: "piece", rayon: "proteines", estimatedPrice: 0.25 },
    ],
  },
  {
    id: "smoothie-proteine-banane-cacahuete",
    name: "Smoothie protéiné banane beurre de cacahuète",
    categories: ["collation", "post-training"],
    portions: 1,
    prepTimeMin: 5,
    difficulty: "facile",
    tags: ["proteine", "rapide", "sans-cuisson", "sans-lactose"],
    calories: 380,
    protein: 28,
    carbs: 35,
    fat: 12,
    ingredients: [
      { name: "Lait d'amande", quantity: 250, unit: "ml", rayon: "laitiers", estimatedPrice: 0.4 },
      { name: "Banane", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 0.3 },
      { name: "Whey protéine", quantity: 1, unit: "cs", rayon: "snacks", estimatedPrice: 0.6 },
      { name: "Beurre de cacahuète", quantity: 1, unit: "cc", rayon: "sauces", estimatedPrice: 0.25 },
    ],
  },
  {
    id: "shaker-whey-flocons-avoine",
    name: "Shaker whey + flocons d'avoine",
    categories: ["post-training", "collation", "rapide"],
    portions: 1,
    prepTimeMin: 3,
    difficulty: "facile",
    tags: ["proteine", "rapide", "sans-cuisson", "budget-bas"],
    calories: 300,
    protein: 30,
    carbs: 30,
    fat: 5,
    ingredients: [
      { name: "Whey protéine", quantity: 1, unit: "cs", rayon: "snacks", estimatedPrice: 0.6 },
      { name: "Flocons d'avoine", quantity: 30, unit: "g", rayon: "feculents", estimatedPrice: 0.15 },
      { name: "Eau ou lait", quantity: 250, unit: "ml", rayon: "laitiers", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "barres-proteinees-maison-avoine-miel",
    name: "Barres protéinées maison avoine miel",
    categories: ["collation", "meal-prep"],
    portions: 6,
    prepTimeMin: 25,
    difficulty: "moyen",
    tags: ["proteine", "meal-prep", "budget-bas"],
    calories: 210,
    protein: 12,
    carbs: 25,
    fat: 7,
    ingredients: [
      { name: "Flocons d'avoine", quantity: 200, unit: "g", rayon: "feculents", estimatedPrice: 0.8 },
      { name: "Miel", quantity: 60, unit: "g", rayon: "epices", estimatedPrice: 0.6 },
      { name: "Whey protéine", quantity: 4, unit: "cs", rayon: "snacks", estimatedPrice: 2.4 },
      { name: "Beurre de cacahuète", quantity: 60, unit: "g", rayon: "sauces", estimatedPrice: 1.0 },
    ],
  },
  {
    id: "yaourt-grec-miel-noix",
    name: "Yaourt grec miel noix",
    categories: ["collation"],
    portions: 1,
    prepTimeMin: 3,
    difficulty: "facile",
    tags: ["proteine", "sans-cuisson", "rapide"],
    calories: 280,
    protein: 18,
    carbs: 20,
    fat: 14,
    ingredients: [
      { name: "Yaourt grec", quantity: 150, unit: "g", rayon: "laitiers", estimatedPrice: 0.7 },
      { name: "Miel", quantity: 1, unit: "cc", rayon: "epices", estimatedPrice: 0.15 },
      { name: "Noix", quantity: 15, unit: "g", rayon: "snacks", estimatedPrice: 0.4 },
    ],
  },
  {
    id: "oeufs-durs-fromage-blanc-fruit",
    name: "Œufs durs + fromage blanc + fruit",
    categories: ["collation", "post-training"],
    portions: 1,
    prepTimeMin: 5,
    difficulty: "facile",
    tags: ["proteine", "sans-cuisson", "rapide", "budget-bas"],
    calories: 260,
    protein: 25,
    carbs: 15,
    fat: 10,
    ingredients: [
      { name: "Œufs durs", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 0.5 },
      { name: "Fromage blanc 0%", quantity: 100, unit: "g", rayon: "laitiers", estimatedPrice: 0.4 },
      { name: "Pomme", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 0.4 },
    ],
  },
  {
    id: "tartare-thon-avocat",
    name: "Tartare de thon avocat",
    categories: ["dejeuner", "rapide"],
    portions: 1,
    prepTimeMin: 12,
    difficulty: "facile",
    tags: ["sans-cuisson", "proteine", "gourmand", "sans-lactose"],
    calories: 420,
    protein: 32,
    carbs: 15,
    fat: 24,
    ingredients: [
      { name: "Thon au naturel (boîte)", quantity: 2, unit: "piece", rayon: "proteines", estimatedPrice: 2.2, store: "Lidl" },
      { name: "Avocat", quantity: 1, unit: "piece", rayon: "fruits", estimatedPrice: 1.0 },
      { name: "Citron, sauce soja", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "poke-bowl-tofu-edamame",
    name: "Poke bowl tofu édamame",
    categories: ["dejeuner"],
    portions: 1,
    prepTimeMin: 20,
    difficulty: "moyen",
    tags: ["vegetarien", "proteine", "gourmand"],
    calories: 500,
    protein: 28,
    carbs: 55,
    fat: 18,
    ingredients: [
      { name: "Tofu ferme", quantity: 120, unit: "g", rayon: "proteines", estimatedPrice: 1.3 },
      { name: "Riz basmati", quantity: 80, unit: "g", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Édamame surgelés", quantity: 60, unit: "g", rayon: "surgeles", estimatedPrice: 0.7, store: "Picard" },
      { name: "Carotte, concombre", quantity: 80, unit: "g", rayon: "legumes", estimatedPrice: 0.4 },
      { name: "Sauce soja sésame", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "chili-con-carne-dinde",
    name: "Chili con carne dinde",
    categories: ["diner", "meal-prep"],
    portions: 3,
    prepTimeMin: 35,
    difficulty: "moyen",
    tags: ["proteine", "budget-bas", "meal-prep", "lidl"],
    calories: 460,
    protein: 35,
    carbs: 40,
    fat: 14,
    ingredients: [
      { name: "Haché de dinde", quantity: 400, unit: "g", rayon: "proteines", estimatedPrice: 4.0, store: "Lidl" },
      { name: "Haricots rouges (boîte)", quantity: 400, unit: "g", rayon: "feculents", estimatedPrice: 1.0, store: "Lidl" },
      { name: "Tomates concassées (boîte)", quantity: 400, unit: "g", rayon: "sauces", estimatedPrice: 0.9, store: "Lidl" },
      { name: "Oignon, épices chili", quantity: 1, unit: "piece", rayon: "epices", estimatedPrice: 0.4 },
    ],
  },
  {
    id: "boulettes-dinde-tomate-riz",
    name: "Boulettes de dinde sauce tomate riz",
    categories: ["diner", "meal-prep"],
    portions: 2,
    prepTimeMin: 30,
    difficulty: "moyen",
    tags: ["proteine", "gourmand", "meal-prep"],
    calories: 540,
    protein: 38,
    carbs: 50,
    fat: 18,
    ingredients: [
      { name: "Haché de dinde", quantity: 300, unit: "g", rayon: "proteines", estimatedPrice: 3.0, store: "Lidl" },
      { name: "Sauce tomate", quantity: 300, unit: "g", rayon: "sauces", estimatedPrice: 0.9 },
      { name: "Riz basmati", quantity: 150, unit: "g", rayon: "feculents", estimatedPrice: 0.5 },
      { name: "Chapelure, ail, persil", quantity: 1, unit: "cs", rayon: "epices", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "saumon-four-legumes-vapeur",
    name: "Saumon au four légumes vapeur",
    categories: ["diner"],
    portions: 1,
    prepTimeMin: 25,
    difficulty: "facile",
    tags: ["proteine", "leger-soir", "sans-gluten", "picard"],
    calories: 420,
    protein: 36,
    carbs: 20,
    fat: 20,
    ingredients: [
      { name: "Pavé de saumon surgelé", quantity: 130, unit: "g", rayon: "surgeles", estimatedPrice: 2.5, store: "Picard" },
      { name: "Légumes vapeur surgelés", quantity: 200, unit: "g", rayon: "surgeles", estimatedPrice: 0.8, store: "Picard" },
      { name: "Citron, herbes", quantity: 1, unit: "piece", rayon: "epices", estimatedPrice: 0.2 },
    ],
  },
  {
    id: "salade-pates-proteinee-poulet",
    name: "Salade de pâtes protéinée poulet",
    categories: ["dejeuner", "meal-prep"],
    portions: 2,
    prepTimeMin: 20,
    difficulty: "facile",
    tags: ["proteine", "meal-prep", "gourmand"],
    calories: 520,
    protein: 36,
    carbs: 55,
    fat: 16,
    ingredients: [
      { name: "Pâtes complètes", quantity: 160, unit: "g", rayon: "feculents", estimatedPrice: 0.6 },
      { name: "Blanc de poulet", quantity: 250, unit: "g", rayon: "proteines", estimatedPrice: 3.0, store: "Lidl" },
      { name: "Tomates cerises, mozzarella light", quantity: 150, unit: "g", rayon: "laitiers", estimatedPrice: 1.5 },
      { name: "Vinaigrette légère", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "wok-legumes-crevettes",
    name: "Wok de légumes crevettes",
    categories: ["diner", "rapide"],
    portions: 1,
    prepTimeMin: 15,
    difficulty: "facile",
    tags: ["leger-soir", "moins-500kcal", "sans-gluten", "picard"],
    calories: 320,
    protein: 28,
    carbs: 25,
    fat: 10,
    ingredients: [
      { name: "Crevettes surgelées", quantity: 120, unit: "g", rayon: "surgeles", estimatedPrice: 2.0, store: "Picard" },
      { name: "Mélange légumes wok surgelés", quantity: 250, unit: "g", rayon: "surgeles", estimatedPrice: 0.9, store: "Picard" },
      { name: "Sauce soja, gingembre", quantity: 1, unit: "cs", rayon: "sauces", estimatedPrice: 0.15 },
    ],
  },
  {
    id: "galettes-pois-chiches-healthy",
    name: "Galettes de pois chiches healthy",
    categories: ["dejeuner", "diner"],
    portions: 2,
    prepTimeMin: 25,
    difficulty: "moyen",
    tags: ["vegetarien", "budget-bas", "sans-gluten", "sans-lactose"],
    calories: 380,
    protein: 18,
    carbs: 45,
    fat: 12,
    ingredients: [
      { name: "Pois chiches (boîte)", quantity: 400, unit: "g", rayon: "feculents", estimatedPrice: 1.0, store: "Lidl" },
      { name: "Oignon, ail, cumin", quantity: 1, unit: "piece", rayon: "epices", estimatedPrice: 0.3 },
      { name: "Farine de pois chiches", quantity: 30, unit: "g", rayon: "feculents", estimatedPrice: 0.3 },
      { name: "Salade verte", quantity: 50, unit: "g", rayon: "legumes", estimatedPrice: 0.4 },
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}
